name: Build and run tests
on:
  push: {}
  pull_request: {}
jobs:
  macos:
    runs-on: macOS-latest
    name: macOS
    steps:
    - uses: actions/checkout@v3
    - name: Xcode version
      run: /usr/bin/xcode-select --print-path
    - name: Build
      run: swift build
    - name: Test
      run: swift test
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        swift-version: [5.5, 5.6, 5.7]
    container: swift:${{ matrix.swift-version }}
    name: Linux
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build --build-tests --enable-test-discovery
    - name: Test
      run: swift test --enable-test-discovery
