name: Build and run tests
on:
  push: {}
  pull_request: {}
jobs:
  macos:
    runs-on: macOS-latest
    name: macOS
    steps:
    - uses: actions/checkout@master
    - name: Xcode version
      run: /usr/bin/xcode-select --print-path
    - name: Build
      run: swift build
    - name: Test
      run: swift test
  linux:
    runs-on: ubuntu-latest
    container: swift:5.3
    name: Linux
    steps:
    - uses: actions/checkout@master
    - name: Build
      run: swift build --build-tests --enable-test-discovery
    - name: Test
      run: swift test --enable-test-discovery